### ISSUE TITLE
Add literal types

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#11]
Literals are represented by `:<identifier>`. These can be used in types. For example a function can always return :ok and the signature will be: `fn foo : :ok`

**Comment by polvalente** [comment]
Could I tackle this one, @emilsoman?

Edit: I took the liberty to try this one out. Sorry if this breaks this repo's workflow!

**Comment by polvalente** [comment]
@emilsoman I noticed that "literal_exps" is a name that's already being used in the parser. Is there any specific reason to not call them atoms?

I reckon it would be better for usability in general, since going to lower-level BEAM would imply mental translations. Furthermore, the fact that the atom table is a limited resource in the BEAM could be hidden behind the name.

edit: This [erl_translate_test](https://github.com/fika-lang/fika/pull/16/files#diff-cb8f4714e7283bea2cc1d4f70a924bddR108-R115) corroborates this issue
