### ISSUE TITLE
String interpolation doesn't compile

### ISSUE THREAD

**Issue by fabionebbia** [fika-lang/fika#45]
To be more precise, it seems like string interpolation does compile as long as:
- the "outer string" is empty (`"<--nothing here-->#{anything}<--nothing here-->"`);
- it's used only once (`"#{first_usage}"` is ok, `"#{first_usage}#{second_usage}"` is not).

Examples:
- Single interpolated string with nothing outside: `"#{"string"}"` compiles ✅
- Single interpolated variable with nothing outside:`"#{var}"` compiles ✅
- Single interpolated string with anything outside: `"Hello #{"World"}"` doesn't compile ❌
- Single interpolated variable with anything outside: `"Hello, #{name}!"` doesn't compile ❌
- Multiple interpolated string/variables with or without anything outside: `"#{var}#{"string"}"` doesn't compile ❌

Note that any of this examples gets parsed as intended, the error seems to arise during type checking.

**Comment by sreecodeslayer** [comment]
This line here: https://github.com/fika-lang/fika/blob/ea8b0ac6c02a534de8efd023a9d1434ad448c26c/lib/fika/type_checker.ex#L154-L162

the Env.scope_get(env, name) expects the env to be a map, but since the accumulator we build inside the reduce_while is `{:ok, _, _env}` tuple, that ends up being given to the `scope_get/2`
